name: stock_predict_on_gcp
channels:
  - defaults
dependencies:
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - click=7.1.2
  - colorama=0.4.3
  - decorator=4.4.2
  - flask=1.1.2
  # - icc_rt=2019.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.17.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - libsodium=1.0.18
  - markupsafe=1.1.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1h
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.2.3
  - prompt-toolkit=3.0.7
  - pygments=2.7.1
  - python=3.8.3
  - python-dateutil=2.8.1
  # - pywin32=227
  - pyzmq=19.0.2
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - threadpoolctl=2.1.0
  - tornado=6.0.4
  - traitlets=5.0.4
  # - vc=14.1
  # - vs2015_runtime=14.16.27012
  - wcwidth=0.2.5
  - werkzeug=1.0.1
  - wheel=0.35.1
  # - wincertstore=0.2
  - zeromq=4.3.2
  - zlib=1.2.11
  - pip:
    - appdirs==1.4.4
    - astroid==2.4.2
    - beautifulsoup4==4.9.3
    - bs4==0.0.1
    - cachetools==4.1.1
    - chardet==3.0.4
    - cssselect==1.1.0
    - fake-useragent==0.1.11
    - google-api-core==1.23.0
    - google-auth==1.23.0
    - google-cloud-core==1.4.3
    - google-cloud-storage==1.32.0
    - google-crc32c==1.0.0
    - google-resumable-media==1.1.0
    - googleapis-common-protos==1.52.0
    - gunicorn==20.0.4
    - idna==2.10
    - isort==5.6.3
    - lazy-object-proxy==1.4.3
    - lxml==4.6.1
    - mccabe==0.6.1
    - pandas==1.1.3
    - parse==1.18.0
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyee==7.0.4
    - pylint==2.6.0
    - pyppeteer==0.2.2
    - pyquery==1.4.1
    - pytz==2020.1
    - requests==2.24.0
    - requests-html==0.10.0
    - rsa==4.6
    - soupsieve==2.0.1
    - toml==0.10.1
    - tqdm==4.50.2
    - urllib3==1.25.11
    - w3lib==1.22.0
    - websockets==8.1
    - wrapt==1.12.1
    - yahoo-fin==0.8.6
    - finta==1.2

